In [1]:
import numpy as np
import json

In [5]:
path = 'Data/yelp_reviews/yelp_academic_dataset_review.json'
file = open(path, encoding ='utf8')

In [6]:
data = []
for i in range(50000):
    data.append(json.loads(file.readline()))

In [8]:
data[0]

{'review_id': 'lWC-xP3rd6obsecCYsGZRg',
 'user_id': 'ak0TdVmGKo4pwqdJSTLwWw',
 'business_id': 'buF9druCkbuXLX526sGELQ',
 'stars': 4.0,
 'useful': 3,
 'funny': 1,
 'cool': 1,
 'text': "Apparently Prides Osteria had a rough summer as evidenced by the almost empty dining room at 6:30 on a Friday night. However new blood in the kitchen seems to have revitalized the food from other customers recent visits. Waitstaff was warm but unobtrusive. By 8 pm or so when we left the bar was full and the dining room was much more lively than it had been. Perhaps Beverly residents prefer a later seating. \n\nAfter reading the mixed reviews of late I was a little tentative over our choice but luckily there was nothing to worry about in the food department. We started with the fried dough, burrata and prosciutto which were all lovely. Then although they don't offer half portions of pasta we each ordered the entree size and split them. We chose the tagliatelle bolognese and a four cheese filled pasta in a 

In [10]:
# Extracting the numerical ratings for each review into a list
# Then convert the list into a numpy array
# Reason to convert to numpy array is that numpy supports more math operations than a list
ratings = np.array([record['stars'] for record in data])
cool = np.array([record['cool'] for record in data])
useful = np.array([record['useful'] for record in data])
funny = np.array([record['funny'] for record in data])

In [12]:
ratings_mean = np.mean(ratings)
ratings_var = np.var(ratings)

print('Ratings Mean: ', ratings_mean)
print('Ratings Variance: ', ratings_var)

Ratings Mean:  3.77406
Ratings Variance:  1.8966911164


In [15]:
# Numpy can also stack multiple arrays together
# Here we stacked [[50k], [50k], [50k]] first
# Then we transpose it into [[x1, x2, x3], .... [x50k, x50k, x50k]]
# This is useful as input for machine learning
stacked = np.stack([cool, funny, useful])
features = stacked.T
features

array([[1, 1, 3],
       [0, 0, 1],
       [0, 0, 0],
       ...,
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [17]:
# For better support of matrix operations, you can also convert from array to matrix type
features = np.matrix(features)
features

matrix([[1, 1, 3],
        [0, 0, 1],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [19]:
# Show the shape of the matrix/array
features.shape

(50000, 3)

In [23]:
# Reshape the matrix into another shape of same elements
features.reshape(3, 50000)

matrix([[1, 1, 3, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 3],
        [3, 4, 0, ..., 0, 0, 0]])